@extends('Layout.master.master')
@section('Upsection')
    @include('Layout.partial.firstsection')
@endsection
@section('newpro')
    @include('Layout.partial.newproducts')
@endsection
@section('hotdeals')
    @include('Layout.partial.hotseals')
@endsection
@section('topselling')
    @include('Layout.partial.topselling')
@endsection
@section('toplist')
    @include('Layout.partial.topsellinglist')
@endsection
@section('news')
    @include('Layout.partial.news')
@endsection
