@extends('Layout.master.master')
@section('Upsection')
    @include('Layout.partial.firstsection')
@endsection
@section('newpro')
    @include('Layout.partial.newproducts')
@endsection
@section('hotdeals')
    @include('Layout.partial.hotseals')
@endsection
